eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


redis:
  topic:
    sign: signServiceTopic
    gateway: gatewayTopic

spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      password: mypass
      timeout: 60000